openapi: 3.2.0
info:
  title: Gravitee.io - Access Management Platform API
  version: 4.12.0-alpha.3
servers:
- url: /management
security:
- gravitee-auth: []
tags:
- name: Platform
paths:
  /platform/audits/events:
    get:
      tags:
      - Platform
      summary: List audit event types
      description: There is no particular permission needed. User must be authenticated.
      operationId: listAuditEventTypes
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /platform/configuration/alerts/status:
    get:
      tags:
      - Platform
      summary: Get the alert service status
      description: There is no particular permission needed. User must be authenticated.
      operationId: getAlertServiceStatus
      responses:
        '200':
          description: Current alert service status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertServiceStatusEntity'
        '500':
          description: Internal server error
  /platform/configuration/flow/schema:
    get:
      tags:
      - Platform
      summary: Get the Policy Studio flow schema
      description: There is no particular permission needed. User must be authenticated.
      operationId: getPolicyStudioFlowSchema
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /platform/configuration/spel/grammar:
    get:
      tags:
      - Platform
      summary: Get the spel grammar
      description: There is no particular permission needed. User must be authenticated.
      operationId: getSpelGrammar
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /platform/configuration/users/email-required:
    get:
      tags:
      - Platform
      operationId: getUserEmailRequired
      responses:
        default:
          description: default response
          content:
            application/json: {}
      summary: Get user email required
      x-summary-source: derived
  /platform/installation:
    get:
      tags:
      - Platform
      summary: Get installation information
      description: User must have the INSTALLATION[READ] permission on the platform
      operationId: getInstallation
      responses:
        '200':
          description: Installation successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallationEntity'
        '404':
          description: No installation has been found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEntity'
        '500':
          description: Internal server error
  /platform/license:
    get:
      tags:
      - Platform
      summary: Get current node License
      operationId: getLicense
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /platform/roles/{role}:
    get:
      tags:
      - Platform
      summary: Get a system role
      description: There is no particular permission needed. User must be authenticated.
      operationId: getSystemRole
      parameters:
      - name: role
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: System role successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '500':
          description: Internal server error
components:
  schemas:
    Role:
      type: object
      properties:
        assignableType:
          type: string
          enum:
          - PLATFORM
          - DOMAIN
          - APPLICATION
          - ORGANIZATION
          - ENVIRONMENT
          - PROTECTED_RESOURCE
        createdAt:
          type: string
          format: date-time
        defaultRole:
          type: boolean
        description:
          type: string
        id:
          type: string
        internalOnly:
          type: boolean
        name:
          type: string
        oauthScopes:
          type: array
          items:
            type: string
        permissionAcls:
          type: object
          additionalProperties:
            uniqueItems: true
            type: array
            items:
              type: string
              enum:
              - CREATE
              - READ
              - LIST
              - UPDATE
              - DELETE
        referenceId:
          type: string
        referenceType:
          type: string
          enum:
          - PLATFORM
          - DOMAIN
          - APPLICATION
          - ORGANIZATION
          - ENVIRONMENT
          - PROTECTED_RESOURCE
        system:
          type: boolean
        updatedAt:
          type: string
          format: date-time
    InstallationEntity:
      type: object
      properties:
        additionalInformation:
          type: object
          additionalProperties:
            type: string
        createdAt:
          type: string
          format: date-time
        id:
          type: string
        updatedAt:
          type: string
          format: date-time
    ErrorEntity:
      type: object
      properties:
        http_status:
          type: integer
          format: int32
        message:
          type: string
    AlertServiceStatusEntity:
      type: object
      properties:
        available:
          type: boolean
  securitySchemes:
    gravitee-auth:
      type: http
      scheme: Bearer
