openapi: 3.0.1
info:
  title: Gravitee.io - Access Management alerts Applications API
  version: 4.12.0-alpha.3
  description: Manage consumer applications
servers:
- url: /management
security:
- gravitee-auth: []
tags:
- name: Applications
  description: Manage consumer applications
paths:
  /environments/{envId}/applications:
    get:
      tags:
      - Applications
      operationId: listApplications
      summary: List Applications
      parameters:
      - $ref: '#/components/parameters/EnvId'
      responses:
        '200':
          description: Applications page
    post:
      tags:
      - Applications
      operationId: createApplication
      summary: Create an Application
      parameters:
      - $ref: '#/components/parameters/EnvId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '201':
          description: Application created
  /environments/{envId}/applications/{applicationId}:
    get:
      tags:
      - Applications
      operationId: getApplication
      summary: Get an Application by Identifier
      parameters:
      - $ref: '#/components/parameters/EnvId'
      - in: path
        name: applicationId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The application
components:
  parameters:
    EnvId:
      in: path
      name: envId
      required: true
      schema:
        type: string
      description: The environment identifier
  schemas:
    Application:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum:
          - SIMPLE
          - BROWSER
          - WEB
          - NATIVE
          - BACKEND_TO_BACKEND
        status:
          type: string
          enum:
          - ACTIVE
          - ARCHIVED
        settings:
          type: object
          properties:
            app:
              type: object
              properties:
                client_id:
                  type: string
                type:
                  type: string
            oauth:
              type: object
  securitySchemes:
    gravitee-auth:
      type: http
      scheme: Bearer
