openapi: 3.0.1
info:
  title: Gravitee.io - Access Management alerts data-sources API
  version: 4.12.0-alpha.3
servers:
- url: /management
security:
- gravitee-auth: []
tags:
- name: data-sources
paths:
  /organizations/{organizationId}/environments/{environmentId}/data-sources:
    get:
      tags:
      - data-sources
      summary: List all the data sources
      description: Returns all of the available data sources to be used in IDP creation
      operationId: listAllDataSources
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List all the IDP data sources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSource'
        '500':
          description: Internal server error
components:
  schemas:
    DataSource:
      type: object
      properties:
        description:
          type: string
        id:
          type: string
        name:
          type: string
  securitySchemes:
    gravitee-auth:
      type: http
      scheme: Bearer
