openapi: 3.0.1
info:
  title: Gravitee.io - Access Management alerts Bot Detection API
  version: 4.12.0-alpha.3
servers:
- url: /management
security:
- gravitee-auth: []
tags:
- name: Bot Detection
paths:
  /platform/plugins/bot-detections:
    get:
      tags:
      - Bot Detection
      summary: List bot detection plugins
      description: There is no particular permission needed. User must be authenticated.
      operationId: listBotDetectionsPlugins
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /platform/plugins/bot-detections/{botDetection}:
    get:
      tags:
      - Bot Detection
      summary: Get a Bot Detection plugin
      description: There is no particular permission needed. User must be authenticated.
      operationId: getBotDetectionPlugin
      parameters:
      - name: botDetection
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /platform/plugins/bot-detections/{botDetection}/schema:
    get:
      tags:
      - Bot Detection
      summary: Get a Bot Detection plugin's schema
      description: There is no particular permission needed. User must be authenticated.
      operationId: getBotDetectionPluginSchema
      parameters:
      - name: botDetection
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /organizations/{organizationId}/environments/{environmentId}/domains/{domain}/bot-detections:
    get:
      tags:
      - Bot Detection
      summary: List registered bot detections for a security domain
      description: User must have the DOMAIN_BOT_DETECTION[LIST] permission on the specified domain or DOMAIN_BOT_DETECTION[LIST] permission on the specified environment or DOMAIN_BOT_DETECTION[LIST] permission on the specified organization Each returned bot detections is filtered and contains only basic information such as id, name.
      operationId: listBotDetections
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List registered bot detections for a security domain
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BotDetection'
        '500':
          description: Internal server error
    post:
      tags:
      - Bot Detection
      summary: Create a bot detection
      description: User must have the DOMAIN_BOT_DETECTION[CREATE] permission on the specified domain or DOMAIN_BOT_DETECTION[CREATE] permission on the specified environment or DOMAIN_BOT_DETECTION[CREATE] permission on the specified organization
      operationId: createBotDetection
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBotDetection'
        required: true
      responses:
        '201':
          description: Bot detection successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotDetection'
        '500':
          description: Internal server error
  /organizations/{organizationId}/environments/{environmentId}/domains/{domain}/bot-detections/{botDetection}:
    get:
      tags:
      - Bot Detection
      summary: Get a bot detection
      description: User must have the DOMAIN_BOT_DETECTION[READ] permission on the specified domain or DOMAIN_BOT_DETECTION[READ] permission on the specified environment or DOMAIN_BOT_DETECTION[READ] permission on the specified organization
      operationId: getBotDetection
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      - name: botDetection
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Bot detection successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotDetection'
        '500':
          description: Internal server error
    put:
      tags:
      - Bot Detection
      summary: Update a bot detection
      description: User must have the DOMAIN_BOT_DETECTION[UPDATE] permission on the specified domain or DOMAIN_BOT_DETECTION[UPDATE] permission on the specified environment or DOMAIN_BOT_DETECTION[UPDATE] permission on the specified organization
      operationId: updateBotDetection
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      - name: botDetection
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBotDetection'
        required: true
      responses:
        '201':
          description: Bot detection successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotDetection'
        '500':
          description: Internal server error
    delete:
      tags:
      - Bot Detection
      summary: Delete a bot detection
      description: User must have the DOMAIN_BOT_DETECTION[DELETE] permission on the specified domain or DOMAIN_BOT_DETECTION[DELETE] permission on the specified environment or DOMAIN_BOT_DETECTION[DELETE] permission on the specified organization
      operationId: deleteBotDetection
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      - name: botDetection
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Bot detection successfully deleted
        '500':
          description: Internal server error
components:
  schemas:
    UpdateBotDetection:
      required:
      - configuration
      - name
      - type
      type: object
      properties:
        configuration:
          type: string
        name:
          type: string
        type:
          minLength: 1
          type: string
    NewBotDetection:
      required:
      - configuration
      - detectionType
      - name
      - type
      type: object
      properties:
        configuration:
          type: string
        detectionType:
          type: string
        id:
          type: string
        name:
          type: string
        type:
          type: string
    BotDetection:
      type: object
      properties:
        configuration:
          type: string
        createdAt:
          type: string
          format: date-time
        detectionType:
          type: string
        id:
          type: string
        name:
          type: string
        referenceId:
          type: string
        referenceType:
          type: string
          enum:
          - PLATFORM
          - DOMAIN
          - APPLICATION
          - ORGANIZATION
          - ENVIRONMENT
          - PROTECTED_RESOURCE
        type:
          type: string
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    gravitee-auth:
      type: http
      scheme: Bearer
