openapi: 3.2.0
info:
  title: Gravitee.io - Access Management Data Plane API
  version: 4.12.0-alpha.3
servers:
- url: /management
security:
- gravitee-auth: []
tags:
- name: Dataplane
paths:
  /organizations/{organizationId}/environments/{environmentId}/data-planes:
    get:
      tags:
      - Dataplane
      summary: List of data planes
      description: List all the data planes accessible to the current user. User must have DATA_PLANE[READ] permission on the specified environment or organization
      operationId: listDataPlanes
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: List accessible data planes for current user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataPlane'
        '500':
          description: Internal server error
components:
  schemas:
    DataPlane:
      type: object
      properties:
        delegate:
          $ref: '#/components/schemas/Plugin'
    Plugin:
      type: object
  securitySchemes:
    gravitee-auth:
      type: http
      scheme: Bearer
