openapi: 3.0.1
info:
  title: Gravitee.io - Access Management alerts audit API
  version: 4.12.0-alpha.3
servers:
- url: /management
security:
- gravitee-auth: []
tags:
- name: audit
paths:
  /organizations/{organizationId}/audits:
    get:
      tags:
      - audit
      summary: List audit logs for the organization
      description: User must have the ORGANIZATION_AUDIT[LIST] permission on the specified organization. Except if user has ORGANIZATION_AUDIT[READ] permission on the organization, each returned audit is filtered and contains only basic information such as id, date, event, actor, target and status.
      operationId: listOrganizationAudits
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      - name: user
        in: query
        schema:
          type: string
      - name: from
        in: query
        schema:
          type: integer
          format: int64
      - name: to
        in: query
        schema:
          type: integer
          format: int64
      - name: size
        in: query
        schema:
          type: integer
          format: int32
          default: 10
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: List audit logs for the platform
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Audit'
        '500':
          description: Internal server error
  /organizations/{organizationId}/audits/{audit}:
    get:
      tags:
      - audit
      summary: Get an audit log
      description: User must have the ORGANIZATION_AUDIT[READ] permission on the specified organization
      operationId: getOrganizationAudit
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: audit
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Audit log successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Audit'
        '500':
          description: Internal server error
  /organizations/{organizationId}/environments/{environmentId}/domains/{domain}/audits:
    get:
      tags:
      - audit
      summary: List audit logs for a security domain
      description: User must have the DOMAIN_AUDIT[LIST] permission on the specified domain, environment or organization. Except if user has ORGANIZATION_AUDIT[READ] permission on the domain, environment or organization, each returned audit is filtered and contains only basic information such as id, date, event, actor, target and status.
      operationId: listDomainAudits
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
      - name: user
        in: query
        schema:
          type: string
      - name: from
        in: query
        schema:
          type: integer
          format: int64
      - name: to
        in: query
        schema:
          type: integer
          format: int64
      - name: size
        in: query
        schema:
          type: integer
          format: int32
          default: 10
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      responses:
        '200':
          description: List audit logs for a security domain
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Audit'
        '500':
          description: Internal server error
  /organizations/{organizationId}/environments/{environmentId}/domains/{domain}/audits/{audit}:
    get:
      tags:
      - audit
      summary: Get an audit log
      description: User must have the DOMAIN_AUDIT[READ] permission on the specified domain or DOMAIN_AUDIT[READ] permission on the specified environment or DOMAIN_AUDIT[READ] permission on the specified organization
      operationId: getDomainAudit
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      - name: environmentId
        in: path
        required: true
        schema:
          type: string
      - name: domain
        in: path
        required: true
        schema:
          type: string
      - name: audit
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Audit log successfully fetched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Audit'
        '500':
          description: Internal server error
components:
  schemas:
    Audit:
      type: object
      properties:
        accessPoint:
          $ref: '#/components/schemas/AuditAccessPoint'
        actor:
          $ref: '#/components/schemas/AuditEntity'
        id:
          type: string
        outcome:
          $ref: '#/components/schemas/AuditOutcome'
        reference:
          $ref: '#/components/schemas/Reference'
        referenceId:
          type: string
        referenceType:
          type: string
          enum:
          - PLATFORM
          - DOMAIN
          - APPLICATION
          - ORGANIZATION
          - ENVIRONMENT
          - PROTECTED_RESOURCE
        target:
          $ref: '#/components/schemas/AuditEntity'
        timestamp:
          type: string
          format: date-time
          writeOnly: true
        transactionId:
          type: string
        type:
          type: string
    AuditOutcome:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
          enum:
          - SUCCESS
          - FAILURE
    AuditAccessPoint:
      type: object
      properties:
        alternativeId:
          type: string
        displayName:
          type: string
        id:
          type: string
        ipAddress:
          type: string
        userAgent:
          type: string
    AuditEntity:
      type: object
      properties:
        alternativeId:
          type: string
        attributes:
          type: object
          additionalProperties:
            type: object
        displayName:
          type: string
        id:
          type: string
        referenceId:
          type: string
        referenceType:
          type: string
          enum:
          - PLATFORM
          - DOMAIN
          - APPLICATION
          - ORGANIZATION
          - ENVIRONMENT
          - PROTECTED_RESOURCE
        type:
          type: string
    Reference:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
          - PLATFORM
          - DOMAIN
          - APPLICATION
          - ORGANIZATION
          - ENVIRONMENT
          - PROTECTED_RESOURCE
  securitySchemes:
    gravitee-auth:
      type: http
      scheme: Bearer
